name: tic-tac-toe

services:
  backend:
    image: backend:latest
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      - CLIENT_URL=https://54.82.5.44:443
    
  frontend:
    image: frontend:latest
    ports:
      - "443:443"
    networks:
      - net
    environment:
      - SERVER_URL=https://54.82.5.44:3000
    depends_on:
      - backend

networks:
  net:
    driver: bridge
